### ISSUE TITLE
[Question] Nextcloud: Difference with the official chart ?

### ISSUE THREAD

**Issue by J3m5** [groundhog2k/helm-charts#100]
Hello, 
I wanted to know, what is the difference between your chart and the [official Nextcloud helm chart](https://github.com/nextcloud/helm/tree/master/charts/nextcloud) ?

**Comment by groundhog2k** [comment]
Hi,

The chart uses my MariaDB , PostgreSQL and Redis chart as dependency. The original Nextcloud chart uses Bitnami charts (https://github.com/nextcloud/helm/blob/master/charts/nextcloud/Chart.yaml).

1. The advantage is that my dependent charts rely on original docker images (not the modified x86 only charts from Bitnami) and support ARM64 and x86. I use this for a multi-arch K8 cluster (DB & Cache on ARM64 with Pi 4 and Nextcloud itself on x86)
2. My chart supports multiple self-defined cron jobs (beside the default cron.php) - f.i.: I added a job for the image preview generator. (`php -f /var/www/html/occ preview:pre-generate`)

**Comment by J3m5** [comment]
Ok,
and beyond the images and the cron jobs, is there any change in configuration ?
I'm asking because of [this issue](https://github.com/nextcloud/helm/issues/10).
Did you encounter it ?

**Comment by groundhog2k** [comment]
No, I don't have the problem described in the issue ticket. I also use NFS (via nfs-client-provisioner) and updated Nextcloud from 19.0.5 to 20.0.2 without any problem.

There is another thing I forgot to mention. All my deployments will run without need of root user in the container and also in unpriviliged read-only mode, because I value security. I don't know if this is a difference to the original nextcloud chart - I can't see such security section (securityContext/podSecurityContex) in the original chart.

**Comment by Janl1** [comment]
@groundhog2k are you running the nextcloud server replicated?

**Comment by groundhog2k** [comment]
Yes.. I have a replicaset of 2 instances with Redis as session cache. 1 MariaDB and 1 Redis on ARM and 2 Nextcloud instances on x86.
Initial setup/installation of Nexcloud was done with one instance and then I updated that deployment to start up a second instance. (Nextcloud itself had problems with 2 instances running in parallel during initial setup dialogs - afterwards it's no problem)
I hope to finish my blog post how I setup my little multi-arch cluster soon.
