### ISSUE TITLE
[postgres] issue with authMethod: "md5"

### ISSUE THREAD

**Issue by untcha** [groundhog2k/helm-charts#811]
Hi Göran,

I'm trying to get paperless-ng (https://github.com/jonaswinkler/paperless-ng) running with a postgres backend. I stumbled upon an issue with the `authMethod` setting.

Background: pagerless-ng or better django is complaining about `SCRAM authentication` when trying to connect to the postgres db.

What I realized is the following. When using:
- postgres chart v0.3.3 and postgres v14.1 with `authMethod: "md5"`, the setting in the `/var/lib/postgresql/data/pg/postgresql.conf` is set to `password_encryption = scram-sha-256`

- postgres chart v0.3.3 and postgres v13.5  with `authMethod: "md5"`, the setting in the `/var/lib/postgresql/data/pg/postgresql.conf` is set to `password_encryption = md5`

With postgres v13.5 the authentication works fine and paperless-ng is working fine.

I tried to apply the setting with the `customConfig`:
```
customConfig: |-
  password_encryption = "md5"
```
Unfortunately this doesn't work because it seems that the `postgresql.conf` file is not mounted correctly in the container:
```
cat: /etc/postgresql/postgresql.conf/: Is a directory
```

Maybe you have an idea how to fix this. Or at least how to apply an custom config and fix the wrong mounted `postgresql.conf` file.

Thanks a lot!

**Comment by groundhog2k** [comment]
Hi Alexander,

setting the `authMethod:` in the helm chart will directly set the environment variable `POSTGRES_HOST_AUTH_METHOD` of the running container. This env. var. is described for the docker image in https://hub.docker.com/_/postgres.

The line you are mentioned in the file `/var/lib/postgresql/data/pg/postgresql.conf` is:
Postgres 13.5:
`#password_encryption = md5              # md5 or scram-sha-256`
Postgres 14.x:
`#password_encryption = scram-sha-256    # scram-sha-256 or md5`

As you see this line is commented out with `#` at the beginning.

It's also not important here because the `POSTGRES_HOST_AUTH_METHOD` will directly influence the setting in the last line of `/var/lib/postgresql/data/pg/pg_hba.conf`

Which is for `authMethod: "md5"`:
`host all all all md5`
for `authMethod: "scram-sha-256"`
`host all all all scram-sha-256`

When no `authMethod:` was specified the default behavior has changed between Postgres 13.5 and 14.x. This is described here https://github.com/docker-library/postgres/issues/911 and here https://github.com/docker-library/postgres/pull/897

One important fact: When the Postgres pod ist started for the first time and created the config files in `/var/lib/postgresql/data/pg` with a specific authMethod setting, the file content will not change later on when the pod is restarted with different authMethod. This is due to the behavior of the scripts in the docker image.

I can only guess, but maybe you stumbled over that behavior of the Postgres docker image when data and configuration already exist in the mounted data directory. 🤷‍♂️ 

Regarding the problem with the mounting of customConfig, you discovered a bug :-) ... Thank you! I will analyze and fix it.


P.S.: For `authMethod:scram-sha-256` the initDbArgs: `--auth-host=scram-sha-256` should be set. It's also described here https://github.com/docker-library/postgres/pull/897

**Comment by groundhog2k** [comment]
@untcha : I hope my answer does help. I will use your ticket to close the bug with the customConfig.

**Comment by untcha** [comment]
@groundhog2k THANKS a lot for your analysis and the information! And of course fixing the bug in the chart 😃 

The information in the table of https://github.com/docker-library/postgres/pull/897 helped a lot.

This did the trick (before I set only the `authMethod`).
```
  ## Postgres database authentication method (default: md5)
  authMethod: "md5"

  ## Optional init database arguments
  initDbArgs: "--auth-host=md5"
```

Again, thanks a lot! 😃
